// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package storage

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createContributors = `-- name: CreateContributors :batchexec
INSERT INTO contributors (name, last_name, email_address) VALUES($1, $2, $3)
`

type CreateContributorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateContributorsParams struct {
	Name         pgtype.Text
	LastName     pgtype.Text
	EmailAddress pgtype.Text
}

func (q *Queries) CreateContributors(ctx context.Context, arg []CreateContributorsParams) *CreateContributorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.LastName,
			a.EmailAddress,
		}
		batch.Queue(createContributors, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateContributorsBatchResults{br, len(arg), false}
}

func (b *CreateContributorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateContributorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createLanguages = `-- name: CreateLanguages :batchexec
INSERT INTO languages (name) VALUES($1)
`

type CreateLanguagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) CreateLanguages(ctx context.Context, name []pgtype.Text) *CreateLanguagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(createLanguages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateLanguagesBatchResults{br, len(name), false}
}

func (b *CreateLanguagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateLanguagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createTags = `-- name: CreateTags :batchexec
INSERT INTO tags (name) VALUES($1)
`

type CreateTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) CreateTags(ctx context.Context, name []pgtype.Text) *CreateTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(createTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateTagsBatchResults{br, len(name), false}
}

func (b *CreateTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteContributors = `-- name: DeleteContributors :batchexec
DELETE FROM contributors WHERE id = $1
`

type DeleteContributorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) DeleteContributors(ctx context.Context, id []pgtype.UUID) *DeleteContributorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(deleteContributors, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteContributorsBatchResults{br, len(id), false}
}

func (b *DeleteContributorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteContributorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteLanguages = `-- name: DeleteLanguages :batchexec
DELETE FROM languages WHERE id = $1
`

type DeleteLanguagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) DeleteLanguages(ctx context.Context, id []pgtype.UUID) *DeleteLanguagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(deleteLanguages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteLanguagesBatchResults{br, len(id), false}
}

func (b *DeleteLanguagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteLanguagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteTags = `-- name: DeleteTags :batchexec
DELETE FROM tags WHERE id = $1
`

type DeleteTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) DeleteTags(ctx context.Context, id []pgtype.UUID) *DeleteTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(deleteTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteTagsBatchResults{br, len(id), false}
}

func (b *DeleteTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
