// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package tagdb

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createTags = `-- name: CreateTags :batchexec
INSERT INTO tags (name) VALUES($1)
`

type CreateTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) CreateTags(ctx context.Context, name []pgtype.Text) *CreateTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(createTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateTagsBatchResults{br, len(name), false}
}

func (b *CreateTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteTags = `-- name: DeleteTags :batchexec
DELETE FROM tags WHERE id = $1
`

type DeleteTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) DeleteTags(ctx context.Context, id []pgtype.UUID) *DeleteTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(deleteTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteTagsBatchResults{br, len(id), false}
}

func (b *DeleteTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
