// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: language.sql

package language

import (
	"context"
)

const listLanguages = `-- name: ListLanguages :many
SELECT id, created_at, updated_at, name FROM languages OFFSET $1 LIMIT $2
`

type ListLanguagesParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListLanguages(ctx context.Context, arg ListLanguagesParams) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
