name: Beaver_ETL CI

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Run Ruff (syntax check)
        run: |
          poetry run ruff backend/apps/beaver_etl

      - name: Run Tests
        run: |
          poetry run pytest backend/apps/beaver_etl/tests
