// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package script

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const delete = `-- name: Delete :batchexec
DELETE FROM scripts WHERE id = $1
`

type DeleteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) Delete(ctx context.Context, id []uuid.UUID) *DeleteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(delete, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteBatchResults{br, len(id), false}
}

func (b *DeleteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const unlinkContributors = `-- name: UnlinkContributors :batchexec
DELETE FROM contributors_scripts WHERE id = $1
`

type UnlinkContributorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UnlinkContributors(ctx context.Context, id []uuid.UUID) *UnlinkContributorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(unlinkContributors, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UnlinkContributorsBatchResults{br, len(id), false}
}

func (b *UnlinkContributorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UnlinkContributorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const unlinkTags = `-- name: UnlinkTags :batchexec
DELETE FROM tags_scripts WHERE id = $1
`

type UnlinkTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UnlinkTags(ctx context.Context, id []uuid.UUID) *UnlinkTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(unlinkTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UnlinkTagsBatchResults{br, len(id), false}
}

func (b *UnlinkTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UnlinkTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
