// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package script

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addContributors = `-- name: AddContributors :batchexec
INSERT INTO contributors_scripts (contributor_id, script_id) VALUES($1, $2)
`

type AddContributorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddContributorsParams struct {
	ContributorID pgtype.UUID
	ScriptID      pgtype.UUID
}

func (q *Queries) AddContributors(ctx context.Context, arg []AddContributorsParams) *AddContributorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ContributorID,
			a.ScriptID,
		}
		batch.Queue(addContributors, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddContributorsBatchResults{br, len(arg), false}
}

func (b *AddContributorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddContributorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const addTags = `-- name: AddTags :batchexec
INSERT INTO tags_scripts (tag_id, script_id) VALUES($1, $2)
`

type AddTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddTagsParams struct {
	TagID    pgtype.UUID
	ScriptID pgtype.UUID
}

func (q *Queries) AddTags(ctx context.Context, arg []AddTagsParams) *AddTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TagID,
			a.ScriptID,
		}
		batch.Queue(addTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddTagsBatchResults{br, len(arg), false}
}

func (b *AddTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createScripts = `-- name: CreateScripts :batchexec
INSERT INTO scripts (title, code, link_to_project, language_id) VALUES($1, $2, $3, $4)
`

type CreateScriptsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateScriptsParams struct {
	Title         pgtype.Text
	Code          pgtype.Text
	LinkToProject pgtype.Text
	LanguageID    pgtype.UUID
}

func (q *Queries) CreateScripts(ctx context.Context, arg []CreateScriptsParams) *CreateScriptsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Title,
			a.Code,
			a.LinkToProject,
			a.LanguageID,
		}
		batch.Queue(createScripts, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateScriptsBatchResults{br, len(arg), false}
}

func (b *CreateScriptsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateScriptsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteScripts = `-- name: DeleteScripts :batchexec
DELETE FROM scripts WHERE id = $1
`

type DeleteScriptsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) DeleteScripts(ctx context.Context, id []uuid.UUID) *DeleteScriptsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(deleteScripts, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteScriptsBatchResults{br, len(id), false}
}

func (b *DeleteScriptsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteScriptsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const removeContributors = `-- name: RemoveContributors :batchexec
DELETE FROM contributors_scripts WHERE id = $1
`

type RemoveContributorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) RemoveContributors(ctx context.Context, id []uuid.UUID) *RemoveContributorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(removeContributors, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RemoveContributorsBatchResults{br, len(id), false}
}

func (b *RemoveContributorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RemoveContributorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const removeTags = `-- name: RemoveTags :batchexec
DELETE FROM tags_scripts WHERE id = $1
`

type RemoveTagsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) RemoveTags(ctx context.Context, id []uuid.UUID) *RemoveTagsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(removeTags, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RemoveTagsBatchResults{br, len(id), false}
}

func (b *RemoveTagsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RemoveTagsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
