// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package script

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContributorsScript struct {
	ID            uuid.UUID
	ContributorID pgtype.UUID
	ScriptID      pgtype.UUID
}

type Script struct {
	ID            uuid.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Title         pgtype.Text
	Code          pgtype.Text
	LinkToProject pgtype.Text
	LanguageID    pgtype.UUID
}

type TagsScript struct {
	ID       uuid.UUID
	TagID    pgtype.UUID
	ScriptID pgtype.UUID
}
