[tool.mypy]
files = "backend/"
ignore_missing_imports = "True"
enable-incomplete-feature= "NewGenericSyntax"
strict_optional = "True"
plugins = ["pydantic.mypy"]


[tool.ruff]
# Never enforce `E501` (line length violations).
lint.ignore = ["E501"]
exclude = [".git", "docs", "build", "dist", "venv"]
line-length = 120
target-version = "py312"
lint.fixable = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "N",
    "Q",
    "S",
    "T",
    "W",
    "ANN",
    "ARG",
    "BLE",
    "COM",
    "DJ",
    "DTZ",
    "EM",
    "ERA",
    "EXE",
    "FBT",
    "ICN",
    "INP",
    "ISC",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "SLF",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "YTT",
]
lint.select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade,
    "I",  # isort
]

[tool.ruff.lint.isort]
lines-after-imports = 2
lines-between-types = 1
section-order = [
    "future",
    "standard-library",
    "first-party",
    "local-folder",
    "third-party",
]
