# Generated by Django 5.0.1 on 2024-06-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codedocument",
            name="link_to_project",
            field=models.URLField(),
        ),
    ]
