# Generated by Django 5.0.1 on 2024-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_api", "0002_alter_codedocument_link_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codedocument",
            name="code",
            field=models.TextField(),
        ),
    ]
