// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contributors.sql

package contributor

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getID = `-- name: GetID :one
SELECT id FROM contributors WHERE email_address=$1
`

func (q *Queries) GetID(ctx context.Context, emailAddress pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getID, emailAddress)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const keepOnly = `-- name: KeepOnly :exec
DELETE FROM contributors WHERE NOT (id = ANY($1::UUID[]))
`

func (q *Queries) KeepOnly(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, keepOnly, ids)
	return err
}

const list = `-- name: List :many
SELECT id, created_at, updated_at, name, last_name, email_address FROM contributors OFFSET $1 LIMIT $2
`

type ListParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]Contributor, error) {
	rows, err := q.db.Query(ctx, list, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contributor
	for rows.Next() {
		var i Contributor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.LastName,
			&i.EmailAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsert = `-- name: Upsert :exec
INSERT INTO contributors (name, last_name, email_address) VALUES($1, $2, $3) ON CONFLICT (email_address) DO NOTHING
`

type UpsertParams struct {
	Name         pgtype.Text
	LastName     pgtype.Text
	EmailAddress pgtype.Text
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) error {
	_, err := q.db.Exec(ctx, upsert, arg.Name, arg.LastName, arg.EmailAddress)
	return err
}
