// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contributors.sql

package contributor

import (
	"context"
)

const listContributors = `-- name: ListContributors :many
SELECT id, created_at, updated_at, name, last_name, email_address FROM contributors OFFSET $1 LIMIT $2
`

type ListContributorsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListContributors(ctx context.Context, arg ListContributorsParams) ([]Contributor, error) {
	rows, err := q.db.Query(ctx, listContributors, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contributor
	for rows.Next() {
		var i Contributor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.LastName,
			&i.EmailAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
