version: "3.8"

services:
  beaver_api_db:
    image: postgres:15.3
    container_name: beaver_api_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: beaver_api
      POSTGRES_PASSWORD: beaver_api
      POSTGRES_DB: beaver_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U films -d films_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2.3
    container_name: redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  postgres_volume:
