// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package contributordb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contributor struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Name         pgtype.Text
	LastName     pgtype.Text
	EmailAddress pgtype.Text
}
