// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package scriptdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contributor struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Name         pgtype.Text
	LastName     pgtype.Text
	EmailAddress pgtype.Text
}

type ContributorsScript struct {
	ID            pgtype.UUID
	ContributorID pgtype.UUID
	ScriptID      pgtype.UUID
}

type Language struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type Script struct {
	ID            pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Title         pgtype.Text
	Code          pgtype.Text
	LinkToProject pgtype.Text
	LanguageID    pgtype.UUID
}

type Tag struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type TagsScript struct {
	ID       pgtype.UUID
	TagID    pgtype.UUID
	ScriptID pgtype.UUID
}
