// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: script.sql

package scriptdb

import (
	"context"
)

const getRandomScript = `-- name: GetRandomScript :one
SELECT id, created_at, updated_at, title, code, link_to_project, language_id FROM scripts LIMIT 1
`

func (q *Queries) GetRandomScript(ctx context.Context) (Script, error) {
	row := q.db.QueryRow(ctx, getRandomScript)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Code,
		&i.LinkToProject,
		&i.LanguageID,
	)
	return i, err
}
