// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package scriptdetail

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contributor struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Name         pgtype.Text
	LastName     pgtype.Text
	EmailAddress pgtype.Text
}

type ContributorsScript struct {
	ID            uuid.UUID
	ContributorID pgtype.UUID
	ScriptID      pgtype.UUID
}

type Language struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type Script struct {
	ID            uuid.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Title         pgtype.Text
	Code          pgtype.Text
	LinkToProject pgtype.Text
	LanguageID    pgtype.UUID
}

type ScriptsDetail struct {
	ScriptID                uuid.UUID
	ScriptTitle             pgtype.Text
	ScriptCode              pgtype.Text
	ScriptLinkToProject     pgtype.Text
	ScriptUpdatedAt         pgtype.Timestamptz
	ScriptCreatedAt         pgtype.Timestamptz
	LanguageID              uuid.UUID
	LanguageName            pgtype.Text
	TagID                   uuid.UUID
	TagName                 pgtype.Text
	ContributorID           uuid.UUID
	ContributorName         pgtype.Text
	ContributorLastName     pgtype.Text
	ContributorEmailAddress pgtype.Text
}

type Tag struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type TagsScript struct {
	ID       uuid.UUID
	TagID    pgtype.UUID
	ScriptID pgtype.UUID
}
