[tool.poetry]
name = "src"
version = "0.1.0"
authors = ["Pavel Eroshkin <eroshkin321@gmail.com>"]
readme = "README.md"
documentation = "https://www.geeksforgeeks.org/weighted-job-scheduling-log-n-time/"
description = "Weighted Interval Planning"
keywords = ["weighted interval scheduling", "dynamic programming", "greedy algorithm"]


[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
