# Generated by Django 5.0.1 on 2024-01-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("language_api", "0001_initial"),
        ("tags_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("code", models.TextField(unique=True)),
                ("link_to_project", models.URLField(unique=True)),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="code_documents",
                        to="language_api.language",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="code_documents", to="tags_api.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
