# Generated by Django 5.0.2 on 2024-03-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codedocument",
            name="code_content_hash",
            field=models.CharField(default="", max_length=64, unique=True),
        ),
    ]
