// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package languagedb

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createLanguages = `-- name: CreateLanguages :batchexec
INSERT INTO languages (name) VALUES($1)
`

type CreateLanguagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) CreateLanguages(ctx context.Context, name []pgtype.Text) *CreateLanguagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(createLanguages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateLanguagesBatchResults{br, len(name), false}
}

func (b *CreateLanguagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateLanguagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteLanguages = `-- name: DeleteLanguages :batchexec
DELETE FROM languages WHERE id = $1
`

type DeleteLanguagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) DeleteLanguages(ctx context.Context, id []pgtype.UUID) *DeleteLanguagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(deleteLanguages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteLanguagesBatchResults{br, len(id), false}
}

func (b *DeleteLanguagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteLanguagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
