// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package languagedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}
