# Generated by Django 5.0.1 on 2024-10-27 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("address", models.EmailField(max_length=256, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
