name: Beaver API CD

on:
  workflow_call:
    inputs:
      api_changed:
        required: true
        type: boolean

jobs:
  prepare_deployment:
    if: inputs.api_changed
    runs-on: ubuntu-latest
    steps:

  deploy_beaver_api:
    needs: prepare_deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run deployment script
        run: |
          chmod +x backend/apps/beaver_api/scripts/deploy.sh
          backend/apps/beaver_api/scripts/deploy.sh
