name: Beaver CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: '**/*.py'
      - uses: chartboost/ruff-action@v1
        with:
          args: check ${{ steps.changed-files.outputs.all_changed_files }} --exit-non-zero-on-fix

  beaver_etl:
    needs: linting
    if: contains(github.event.head_commit.message, 'backend/apps/beaver_etl') || contains(github.event.pull_request.changed_files, 'backend/apps/beaver_etl/')
    uses: ./.github/workflows/beaver_etl.yml
