name: Beaver CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    if: contains(github.event.head_commit.message, 'backend') || contains(github.event.pull_request.changed_files, 'backend/')
    uses: ./.github/workflows/backend.yml
    with:
      ref: master
